# Working with Numpy - for mathematical operations

In [11]:
import numpy as np

In [12]:
# Type 1 array
a = np.array([1, 2, 3, 4, 5])

print(type(a))

print(a.shape)

print(a)

print(a.size)

<class 'numpy.ndarray'>
(5,)
[1 2 3 4 5]
5


In [13]:
# type 2 array
b = np.array([[1], [2], [3], [4]])
# b = np.array([1], [2], [3], [4])

print(b)

# shape
print(b.shape)

print(b.size)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
4


In [14]:
b[0][0]

1

In [15]:
b[1][0]

2

In [16]:
# type 3 array
c = np.array([[1, 2, 3], [4, 5, 6]])

print(c)

print(c.shape)

print(c[1][1])

print(c.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
5
6


In [17]:
# 
d = np.zeros((3, 3))
e = np.ones((2, 3))


print(d)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# Array of constants
f = np.full([3, 2], 8)

print(f)

[[8 8]
 [8 8]
 [8 8]]


In [19]:
# identity matrix
d = np.eye(4)

print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
# Random matrix

random_matrix = np.random.random([2, 3])

print(random_matrix)

[[0.56813027 0.54121996 0.13315827]
 [0.37978933 0.31286111 0.52789466]]


In [21]:
# reading the elements of first column
print(random_matrix[ : , 1])

[0.54121996 0.31286111]


In [22]:
# reading the elemetns of second column
print(random_matrix[ : , 2])

[0.13315827 0.52789466]


In [23]:
# edit the last two elements of the second row
random_matrix[1, 1: ] = 1

print(random_matrix)

[[0.56813027 0.54121996 0.13315827]
 [0.37978933 1.         1.        ]]


In [24]:
random_matrix[1, 1: 3] = 1

print(random_matrix)

[[0.56813027 0.54121996 0.13315827]
 [0.37978933 1.         1.        ]]


In [25]:
random_matrix[1, 0: 3] = 1

print(random_matrix)

[[0.56813027 0.54121996 0.13315827]
 [1.         1.         1.        ]]


In [26]:
## set some rows and columns
z = np.zeros((3, 3))

print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# editing the matrix by making all the first row 5
z[1, : ] = 5

print(z)

[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


In [28]:
# editing the matrix
z[:, -1] = 7

print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [29]:
# data types
print(z.dtype)

float64


In [30]:
# converting it into int type
z = np.zeros((3, 3), np.int)

print(z.dtype)

int32


In [31]:
# mathematical operations on numpy
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# adding 
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [32]:
# subtracting 
print(x - y)

print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [33]:
# multiplication
print(x * y)

print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [34]:
# divide 
print(x / y)

print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:
# modulus
print(x % y)

print(np.mod(x, y))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [36]:
# matrix multiplication and dot product 
print(x)
print(y)

print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [37]:
# multiplication dot product of vector is scalar
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print(a.dot(b))

30


In [38]:
print(a)

[1 2 3 4]


In [39]:
# sum funciton
print(sum(a))

print(np.sum(a))

10
10


In [40]:
print(x)

[[1 2]
 [3 4]]


In [41]:
# columnwise sum 


[4 6]


In [42]:
# rowwise sum
print(np.sum(x, axis = 1))

[3 7]


In [43]:
# stacking of arrays
print(a)

b = b ** 2

print(b)

[1 2 3 4]
[ 1  4  9 16]


In [44]:
np.stack((a, b), axis = 0)

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [45]:
np.stack((a, b), axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [50]:
# reshape the numpy array
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])

a = np.stack((a, b), axis = 0)
print(a)

a = a.reshape((4, 2))

print(a)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [52]:
print(a.reshape((8, 1)))
a

[[1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [3]
 [4]]


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [48]:
print(a.reshape((4, -1)))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [49]:
print(a.reshape((-1, 4)))

[[1 2 3 4]
 [1 2 3 4]]


In [42]:
print(10)

10


# Important notes
- shape shows the dimension and size shows the number of elements