# Numpy Random Module
- arange: to make a simple array of our type
- rand: to make a random array
- randn
- randint
- seed: to prevent the shuffle (np.random.seed(1))
- random: for executing random commands
- choice: random choice
- Shuffle: shuffling the array

In [1]:
import numpy as np

In [2]:
# array of first 10 nos
a = np.arange(10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# array starting from 5
a = np.arange(10) + 5

print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [4]:
# shuffling the array randomly
np.random.shuffle(a)

print(a)

[ 9 10 14  7  6 13  5 11  8 12]


In [5]:
# returns values from a standard normal distrubution 
# making the random array using rand function
a = np.random.rand(2, 3)

print(a)

[[0.58945365 0.30823622 0.3917253 ]
 [0.62391863 0.29045351 0.87765985]]


In [36]:
b = np.random.rand(5, 10, 3)

print(b)

[[[0.86392893 0.71912259 0.53661059]
  [0.61655165 0.62976009 0.79032389]
  [0.89311653 0.73614061 0.54649236]
  [0.13380472 0.01773027 0.02833972]
  [0.55161307 0.22661286 0.86283269]
  [0.85039132 0.8767862  0.58309849]
  [0.14219612 0.46579982 0.13556775]
  [0.48880912 0.71461727 0.43926571]
  [0.50395072 0.85101358 0.92514816]
  [0.7115258  0.06576472 0.44277344]]

 [[0.52539789 0.68235141 0.31326933]
  [0.00603284 0.27075535 0.76320296]
  [0.37880512 0.16005573 0.29396068]
  [0.78387446 0.87323676 0.70646944]
  [0.98210873 0.51888981 0.16014413]
  [0.17514907 0.96370419 0.48055919]
  [0.03009923 0.73360595 0.40245348]
  [0.45868489 0.85756459 0.61842718]
  [0.09420253 0.22681904 0.15213963]
  [0.04507633 0.67872167 0.65609548]]

 [[0.54154809 0.54669571 0.77946792]
  [0.62170429 0.23536754 0.48622461]
  [0.93787368 0.51884708 0.30632523]
  [0.11841825 0.62693634 0.96091349]
  [0.16222558 0.07198963 0.69647638]
  [0.54571841 0.35962229 0.56068465]
  [0.71707761 0.65529278 0.5819869

In [40]:
# randomly pick one element from an array
element = np.random.choice([4, 3, 2, 11, 27])

print(element)

11
