# Some More Numpy Functions - Statistics
- min, max
- mean
- median
- average 
- variance
- standard deviation

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4], [7, 8, 9, 0]])
print(a)

[[1 2 3 4]
 [7 8 9 0]]


In [3]:
# min
print(np.min(a))

print(np.min(a, axis = 0))

print(np.min(a, axis = 1))

0
[1 2 3 0]
[1 0]


In [4]:
# max
print(np.max(a))

print(np.max(a, axis = 0))

print(np.max(a, axis = 1))

9
[7 8 9 4]
[4 9]


In [5]:
# mean
b = np.array([1, 2, 3, 4, 5])

m = sum(b) / 5

print(m)

3.0


In [6]:
c = np.mean(b)

print(c)

3.0


In [16]:
a = np.array([[1, 2, 3, 4], [7, 8, 9, 0]])
print(a)
print(np.mean(a))

print(np.mean(a, axis = 0))

print(np.mean(a, axis = 1))

[[1 2 3 4]
 [7 8 9 0]]
4.25
[4. 5. 6. 2.]
[2.5 6. ]


In [20]:
# median
c = np.array([1, 5, 4, 2, 0])
print(sorted(c))
print(np.median(c))

[0, 1, 2, 4, 5]
2.0


In [9]:
# mean vs average 
print(np.mean(c))

# avreage is weighted
w = np.array([1, 2, 3, 4, 5])

print(np.average(c, weights = w))
# (1*1 + 2*5 + 3*4 + 4*2 + 5*0)/(1+2+3+4+5)

# if w has only 1, this mean it is calulating the mean only
w = np.array([1, 1, 1, 1, 1])

print(np.average(c, weights = w))

2.4
2.066666666666667
2.4


In [10]:
# standard deviation
u = np.mean(c)

mystd = np.sqrt(np.mean(abs(c - u) ** 2))
# formula for standard deviation is 
    

print(mystd)

1.854723699099141


In [11]:
#  inbuilt function
dev = np.std(c)

print(dev)

1.854723699099141


In [12]:
# variance 
print(mystd ** 2)

print(np.var(c))

3.440000000000001
3.4400000000000004


In [13]:
z = np.array([])
print(z)

[]
