# Pandas Basics -1
Dataframe = tabular storage of data(rows & columns)

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
# here I put the min(1) and max(100) marks along with the no of students(5) in MarksA
np.random.randint(1, 100, 5)

array([41, 78,  3, 54,  1])

In [6]:
# let's create dataframe
user_data = {
    "MarksA" : np.random.randint(1, 100,5),
    "MarksB" : np.random.randint(50, 100,5),
    "MarksC" : np.random.randint(1, 100,5)
}

In [7]:
user_data

{'MarksA': array([19, 67, 20,  4, 76]),
 'MarksB': array([59, 65, 72, 92, 55]),
 'MarksC': array([71, 57,  3, 96, 74])}

In [8]:
df = pd.DataFrame(user_data)
df

MarksA  MarksB  MarksC
0      19      59      71
1      67      65      57
2      20      72       3
3       4      92      96
4      76      55      74

In [9]:
# in floating point 
df = pd.DataFrame(user_data, dtype = 'float32')
df

MarksA  MarksB  MarksC
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0
3     4.0    92.0    96.0
4    76.0    55.0    74.0

In [10]:
# by default it shows data for the first rows
df.head()

MarksA  MarksB  MarksC
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0
3     4.0    92.0    96.0
4    76.0    55.0    74.0

In [11]:
# we can mention that we want data upto our choice
df.head(n = 3)

MarksA  MarksB  MarksC
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0

In [12]:
# for columns
df.columns

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')

In [13]:
# creating the csv
df.to_csv('marks.csv')

In [14]:
# reading the csv
my_data = pd.read_csv('marks.csv')
my_data

Unnamed: 0  MarksA  MarksB  MarksC
0           0    19.0    59.0    71.0
1           1    67.0    65.0    57.0
2           2    20.0    72.0     3.0
3           3     4.0    92.0    96.0
4           4    76.0    55.0    74.0

In [15]:
# removing the unwanted first column
my_data = pd.read_csv('marks.csv')
my_data = my_data.drop(columns = ['Unnamed: 0'])
my_data

MarksA  MarksB  MarksC
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0
3     4.0    92.0    96.0
4    76.0    55.0    74.0

# Pandas Basics-2

In [16]:
# to check the average score of the class
my_data.describe()
# count denotes how many entries are there in each row

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   37.200000  68.600000  60.200000
std    32.104517  14.570518  34.895558
min     4.000000  55.000000   3.000000
25%    19.000000  59.000000  57.000000
50%    20.000000  65.000000  71.000000
75%    67.000000  72.000000  74.000000
max    76.000000  92.000000  96.000000

In [17]:
# displays the first 5 rows
my_data.head()

MarksA  MarksB  MarksC
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0
3     4.0    92.0    96.0
4    76.0    55.0    74.0

In [18]:
# displays last 5 rows
my_data.tail()

MarksA  MarksB  MarksC
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0
3     4.0    92.0    96.0
4    76.0    55.0    74.0

In [19]:
my_data.tail(n = 3)

MarksA  MarksB  MarksC
2    20.0    72.0     3.0
3     4.0    92.0    96.0
4    76.0    55.0    74.0

In [20]:
# access a particular 
df.iloc[3]# i stands for interger & loc stands for location

MarksA     4.0
MarksB    92.0
MarksC    96.0
Name: 3, dtype: float32

In [21]:
# to access a particular row & column
df.iloc[3, 1]
# we can do df.iloc[3][1] also

92.0

In [22]:
# to find the index of the column 
idx = df.columns.get_loc('MarksB')
print(idx)

1


In [23]:
# from there I got the index
df.iloc[3, idx]

92.0

In [24]:
# doing the above call for the two columns
idx = [df.columns.get_loc('MarksB'), df.columns.get_loc('MarksC')]
print(idx)
df.iloc[3, idx]

[1, 2]


MarksB    92.0
MarksC    96.0
Name: 3, dtype: float32

In [26]:
df.iloc[:3, idx]

MarksB  MarksC
0    59.0    71.0
1    65.0    57.0
2    72.0     3.0

In [28]:
df.iloc[:3, [1, 2]]

MarksB  MarksC
0    59.0    71.0
1    65.0    57.0
2    72.0     3.0

In [30]:
# Sort for dataframe
my_data

MarksA  MarksB  MarksC
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0
3     4.0    92.0    96.0
4    76.0    55.0    74.0

In [32]:
my_data.sort_values(by = ["MarksA"], ascending = True)

MarksA  MarksB  MarksC
3     4.0    92.0    96.0
0    19.0    59.0    71.0
2    20.0    72.0     3.0
1    67.0    65.0    57.0
4    76.0    55.0    74.0

In [35]:
my_data.sort_values(by = ["MarksC", "MarksA"], ascending = False)

MarksA  MarksB  MarksC
3     4.0    92.0    96.0
4    76.0    55.0    74.0
0    19.0    59.0    71.0
1    67.0    65.0    57.0
2    20.0    72.0     3.0

In [37]:
data_array = my_data.values

print(type(my_data))

print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [38]:
print(data_array)

[[19. 59. 71.]
 [67. 65. 57.]
 [20. 72.  3.]
 [ 4. 92. 96.]
 [76. 55. 74.]]


In [40]:
print(type(data_array))

<class 'numpy.ndarray'>


In [41]:
data_array.shape

(5, 3)

In [42]:
data_array[2][2]

3.0

In [44]:
# numpy array back into pandas dataframe
new_df = pd.DataFrame(data_array, dtype = 'int32', columns = ["Physics", "Chem", "Maths"])
new_df

Physics  Chem  Maths
0       19    59     71
1       67    65     57
2       20    72      3
3        4    92     96
4       76    55     74

In [46]:
new_df.to_csv('PCM.csv')

In [47]:
new_df.to_csv('PCM.csv', index = False)

In [48]:
pcm = pd.read_csv('PCM.csv')

In [49]:
print(pcm)

   Physics  Chem  Maths
0       19    59     71
1       67    65     57
2       20    72      3
3        4    92     96
4       76    55     74
