# Broadcasting 
- You can add a scalar to a vector, and numpy will add it to each element to vector
 - x + a = xi + a
- Similarly you can add a vector to a matrix, and numpy will add the vector to each column of the matrix

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


In [4]:
x = np.array([1, 2, 3, 4])
print(x)
print(x + 4)

[1 2 3 4]
[5 6 7 8]


In [5]:
X = np.array([[10, 20, 30, 40], [40, 50, 60, 70]])

print(X)

print(X + x)

[[10 20 30 40]
 [40 50 60 70]]
[[11 22 33 44]
 [41 52 63 74]]


# Matrix Multiplication 

In [7]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[0, 2], 
              [3, 2]])

A * B

array([[0, 4],
       [9, 8]])

In [8]:
np.dot(A, B)

array([[ 6,  6],
       [12, 14]])