# Norms

## L^2 norm is called the Euclidean Norm

In [2]:
import numpy as np

In [3]:
# calculating the norms of vectors
x = np.array([3, 4])

lp2 = np.linalg.norm(x)
print(lp2)

lp1 = np.linalg.norm(x, ord = 1)
print(lp1)

lpinf = np.linalg.norm(x, ord = np.inf)
print(lpinf)

5.0
7.0
4.0


In [4]:
x = np.array([-3, -4])

lp2 = np.linalg.norm(x)
print(lp2)

lp1 = np.linalg.norm(x, ord = 1)
print(lp1)

5.0
7.0


In [5]:
# for better understanding of norms

x = np.array([12, 5])

l1 = np.linalg.norm(x, ord = 1)
print(l1)

# l2 norm is called euclidean norm
l2 = np.linalg.norm(x, ord = 2)
print(l2)

l3 = np.linalg.norm(x, ord = 3)
print(l3)

# infinity norm is always the greater value
linf = np.linalg.norm(x, ord = 
                      np.inf)
print(linf)


17.0
13.0
12.28264235951734
12.0


# Determinants

In [6]:
A = np.array([[1, 2], 
              [3, 4]])
np.linalg.det(A)

-2.0000000000000004

In [3]:
a = np.array([[1, 2, 3],
             [2, 3, 1], 
             [3, 1, 2]])
print(np.linalg.det(a))

-17.999999999999996


# Inverse
Use either np.linalg.inv() or np.linalg.pinv()

In [7]:
Ainv = np.linalg.inv(A)

print(Ainv)

print(np.dot(A, Ainv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [10]:
pinv = np.linalg.pinv(A)

print(pinv)

print(np.dot(A, pinv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.00000000e+00 -6.66133815e-16]
 [ 1.77635684e-15  1.00000000e+00]]


In [29]:
A = np.array([[6, 8], 
              [3, 4]])

pinv = np.linalg.pinv(A)

print(pinv)

print(np.dot(A, pinv))

[[0.048 0.024]
 [0.064 0.032]]
[[0.8 0.4]
 [0.4 0.2]]


In [30]:
A = np.array([[1, 2], 
              [3, 4]])
Ainv = np.linalg.inv(A)

print(Ainv)

pinv = np.linalg.pinv(A)

print(pinv)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


# Solve a System of Equations

In [32]:
a = np.array([[2, 3], [3, 1]])
b = np.array([8, 5])

In [33]:
np.linalg.solve(a, b)

array([1., 2.])